Empty AdminModels as StackedInlines causing crashes
Example:

models.py:

class Profile(models.Model):
    user = models.OneToOneField(User)

admin.py:

from django.contrib.auth.admin import UserAdmin
from models import Profile

class ProfileInline(admin.StackedInline):
    model = Profile

class CustomUserAdmin(UserAdmin):
    inlines = (ProfileInline, )

admin.site.unregister(User)
admin.site.register(User, CustomUserAdmin)

---------------------

Clicking on the "User" object in the admin under native django admin you will
see a line with the Profile object and its id.  Under
django-admin-bootstrapped you get an exception:

ValueError: max() arg is an empty sequence

inside of the bootstrapped_goodies_tags.py file.

Upon further inspection it looks like fieldset_column_width() and
form_fieldset_column_width() both assume there are fields in the fieldset.
The column_width() method makes a similar assumption which could cause a
divide by zero problem.

Wrapped max() and division calls to stop these problems.